### ISSUE TITLE
BentoBox failed thread check for reason: Asynchronous Chunk getEntities call

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Limits#135]
#### Describe the bug

Player is trying to spawn an Iron Golem.
Result: no golem + error on console
<details>
  <summary>Error message, click to open</summary>
  
 ```
[11:33:18 FATAL]: Thread Craft Scheduler Thread - 796 - BentoBox failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Purpur-1292]
at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2360) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1173) ~[patched_1.17.1.jar:git-Purpur-1292]
at world.bentobox.limits.listeners.EntityLimitListener.atLimit(EntityLimitListener.java:441) ~[?:?]
at world.bentobox.limits.listeners.EntityLimitListener.lambda$processIsland$7(EntityLimitListener.java:224) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
at world.bentobox.limits.listeners.EntityLimitListener.processIsland(EntityLimitListener.java:222) ~[?:?]
at world.bentobox.limits.listeners.EntityLimitListener.lambda$checkLimit$4(EntityLimitListener.java:215) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1292]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1292]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1292]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
[11:33:18 WARN]: [BentoBox] Plugin BentoBox v1.17.1-SNAPSHOT-b2097 generated an exception while executing task 134086
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Purpur-1292]
at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2360) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1173) ~[patched_1.17.1.jar:git-Purpur-1292]
at world.bentobox.limits.listeners.EntityLimitListener.atLimit(EntityLimitListener.java:441) ~[?:?]
at world.bentobox.limits.listeners.EntityLimitListener.lambda$processIsland$7(EntityLimitListener.java:224) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
at world.bentobox.limits.listeners.EntityLimitListener.processIsland(EntityLimitListener.java:222) ~[?:?]
at world.bentobox.limits.listeners.EntityLimitListener.lambda$checkLimit$4(EntityLimitListener.java:215) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1292]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1292]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1292]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
 ```
 
 </details>

#### Steps to reproduce the behavior

Place iron blocks in a T-shape and then a carved pumpkin on top
I haven't found a way to reproduce it on a default test server

#### Expected behavior

Golem should spawn

##### Output of `/bbox version` (Mandatory)

```
[12:01:27 INFO]: Running PURPUR 1.17.1.
[12:01:27 INFO]: BentoBox version: 1.17.1-SNAPSHOT-b2097
[12:01:27 INFO]: Database: JSON
[12:01:27 INFO]: Loaded Game Worlds:
[12:01:27 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[12:01:27 INFO]: Loaded Addons:
[12:01:27 INFO]: Biomes 1.14.1-SNAPSHOT-b209 (ENABLED)
[12:01:27 INFO]: BSkyBlock 1.15.0 (ENABLED)
[12:01:27 INFO]: Challenges 0.9.0-SNAPSHOT-b457 (ENABLED)
[12:01:27 INFO]: Level 2.7.0-SNAPSHOT-b465 (ENABLED)
[12:01:27 INFO]: Limits 1.17.1-SNAPSHOT-b266 (ENABLED)
[12:01:27 INFO]: MagicCobblestoneGenerator 2.4.0-SNAPSHOT-b228 (ENABLED)
[12:01:27 INFO]: Warps 1.11.1-SNAPSHOT-b294 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
A quick workaround while I fix this is to change this setting in the Limits config.yml to false:

```
# Use async checks for snowmen and iron golums. Set to false if you see problems.
async-golums: false
```

**Comment by x1p** [comment]
Setting `async-golums: false` works indeed. I missed that config entry because there was no entry in my config file. I was so used that config files updated themself upon updating bentobox and add-ons. But this one apparently didn't update.

**Comment by tastybento** [comment]
The latest snapshot should work as well.
