### ISSUE TITLE
Some errors on 2216 dev version

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Limits#157]
### Expected behavior

No error.

### Observed/Actual behavior

```
[17:11:31 ERROR]: Could not pass event CreatureSpawnEvent to BentoBox v1.20.0-SNAPSHOT-b2216
java.lang.NullPointerException: Cannot invoke "world.bentobox.limits.objects.IslandBlockCount.getEntityLimitOffset(org.bukkit.entity.EntityType)" because "ibc" is null
        at world.bentobox.limits.listeners.EntityLimitListener.atLimit(EntityLimitListener.java:409) ~[?:?]
        at world.bentobox.limits.listeners.EntityLimitListener.processIsland(EntityLimitListener.java:178) ~[?:?]
        at world.bentobox.limits.listeners.EntityLimitListener.checkLimit(EntityLimitListener.java:169) ~[?:?]
        at world.bentobox.limits.listeners.EntityLimitListener.onCreatureSpawn(EntityLimitListener.java:122) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1481.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:git-Pufferfish-35]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:729) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:634) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1422) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1334) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:319) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:236) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:194) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1052) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:926) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:625) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1609) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1266) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:11:31 ERROR]: Could not pass event CreatureSpawnEvent to BentoBox v1.20.0-SNAPSHOT-b2216
java.lang.NoSuchFieldError: DEEP_WARM_OCEAN
        at world.bentobox.extramobs.listeners.MobsSpawnListener.onEntitySpawn(MobsSpawnListener.java:118) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1438.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:git-Pufferfish-35]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:729) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:634) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1422) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1334) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:319) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:236) ~[?:?]
        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:194) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1052) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:926) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:625) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1609) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1266) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-35]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

I just created an island.

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/150541653-25e5ea08-04a2-4f6c-9857-4e455bdd79e1.png)

**Comment by tastybento** [comment]
@OverBrave Please try 1.19.1-SNAPSHOT of Limits to confirm this is fixed.
