### ISSUE TITLE
Unable to build snow golem and iron golem regardless of any limit set

### ISSUE THREAD

**Issue by Ritcheur** [BentoBoxWorld/Limits#180]
### Expected behavior

If no limit is set on snow golem or iron golem, one can spawn as many as they want by building them.

### Observed/Actual behavior

Regardless of any limit set, we are unable to spawn any snow golem or iron golem when the Limits addon is active.

### Steps/models to reproduce

- Have the BentoBox plugin and Limits addon active.
- Set up the limits' config file however you like (it can be left empty).
- Try building a snow golem or an iron golem.
- The blocks do not disappear, and no mob spawns.

### BentoBox version

Server : PAPER 1.20.4
BentoBox : b2510 and b2521 (maybe other versions)
Limits : 1.19.1-b301, 1.19.2-b319 and 1.20.0-b321 (maybe other versions)

Details : 
Server PAPER 1.20.4
BentoBox : 2.0.0-SNAPSHOT-b2521
DB : JSON2MARIADB
bskyblock_world (BSkyBlock) : Overworld, Nether, End
Biomes 2.2.0-SNAPSHOT-b256
CauldronWitchery 2.0.2-SNAPSHOT-#59
Challenges 1.3.0-SNAPSHOT-b538
Chat 1.1.4
ControlPanel 1.13.0
DimensionalTrees 1.6.0
ExtraMobs 1.12
Greenhouses 1.7.4-SNAPSHOT-b364
Level 2.12.0-SNAPSHOT-b555
Limits 1.20.0-SNAPSHOT-b321
MagicCobblestoneGenerator 2.5.2-SNAPSHOT-b271
Upgrades 0.3.0-SNAPSHOT-b131
Warps 1.14.0-SNAPSHOT-b357

**Comment by tastybento** [comment]
This error occurs in the console:

```
[12:03:18 WARN]: [BentoBox] Task #47 for BentoBox v2.0.0-SNAPSHOT-LOCAL generated an exception
java.lang.IllegalArgumentException: Cannot spawn an entity for org.bukkit.craftbukkit.v1_20_R3.entity.CraftIronGolem
	at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.createEntity(CraftRegionAccessor.java:493) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.spawn(CraftRegionAccessor.java:411) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.spawn(CraftRegionAccessor.java:407) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.spawn(CraftRegionAccessor.java:398) ~[paper-1.20.4.jar:git-Paper-370]
	at world.bentobox.limits.listeners.EntityLimitListener.lambda$processIsland$5(EntityLimitListener.java:183) ~[Limits-1.20.0-SNAPSHOT-b321.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1639) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-370]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by tastybento** [comment]
I'm filing a Spigot bug on this as it seems to be a server issue.

**Comment by tastybento** [comment]
Filed as https://hub.spigotmc.org/jira/browse/SPIGOT-7565

**Comment by tastybento** [comment]
md5 says that I need to use a different API, so that's in progress. That yielded another bug https://hub.spigotmc.org/jira/browse/SPIGOT-7567

**Comment by tastybento** [comment]
md5 fixed the snowman bug but you'll need to wait for it to get into a release before it works. In the meantime, snowmen will spawn but leave behind blocks, which may suffocate them. That said, this update will work for Iron Golems and Withers fine now. You can get the latest from ci.bentobox.world. I'll do a release this weekend once the Spigot bug fix has made it to Paper, etc.
