### ISSUE TITLE
[ERROR] MELON_STEM isn't an item

### ISSUE THREAD

**Issue by myavuzokumus** [BentoBoxWorld/Limits#191]
### Expected behavior

Need to be working without problem :D

### Observed/Actual behavior

```
[Server thread/ERROR]: Command exception: /is limits
java.lang.IllegalArgumentException: MELON_STEM isn't an item
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.inventory.ItemStack.of(ItemStack.java:69) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:149) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at BentoBox-2.4.1.jar/world.bentobox.bentobox.api.panels.builders.PanelItemBuilder.icon(PanelItemBuilder.java:40) ~[BentoBox-2.4.1.jar:?]
	at Limits-1.21.0-1720901519801.jar/world.bentobox.limits.commands.player.LimitTab.addMaterialIcons(LimitTab.java:185) ~[Limits-1.21.0-1720901519801.jar:?]
	at Limits-1.21.0-1720901519801.jar/world.bentobox.limits.commands.player.LimitTab.<init>(LimitTab.java:81) ~[Limits-1.21.0-1720901519801.jar:?]
	at Limits-1.21.0-1720901519801.jar/world.bentobox.limits.commands.player.LimitPanel.showLimits(LimitPanel.java:69) ~[Limits-1.21.0-1720901519801.jar:?]
	at Limits-1.21.0-1720901519801.jar/world.bentobox.limits.commands.player.PlayerCommand.execute(PlayerCommand.java:49) ~[Limits-1.21.0-1720901519801.jar:?]
	at BentoBox-2.4.1.jar/world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:292) ~[BentoBox-2.4.1.jar:?]
	at BentoBox-2.4.1.jar/world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:260) ~[BentoBox-2.4.1.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1568) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1545) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1538) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1497) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1504) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1349) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2264-bf63cfa]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
````

### Steps/models to reproduce

Put `PUMPKIN_STEM` or `MELON_STEM` to under of blocklimits section in the config.

### BentoBox version

BBOX version: 2.4.1
Limits: 1.21.0
Current Purpur Version: 1.21-2264-bf63cfa (MC: 1.21)*

**Comment by tastybento** [comment]
Should be fixed in latest SNAPSHOT build on ci.bentobox.world. This is actually a long-standing bug because the idea of limited melons (which have to be done via MELON_STEM) had not been anticipated.

**Comment by myavuzokumus** [comment]
The problem is fixed, thank you!
