### ISSUE TITLE
EpicSpawners error - Could not pass event SpawnerBreakEvent to BentoBox v1.5.2

### ISSUE THREAD

**Issue by Deathinflames** [BentoBoxWorld/Limits#25]
#### Describe the bug

I noticed this in the console when using BentoBox v1.5.2, Limits 0.2.1, and EpicSpawners v6-Pre-release-10.
https://pastebin.com/raw/criSW5iH

#### Steps to reproduce the behavior

It seems to happen while breaking spawners and using the epic spawners plugin combined with the BentoBox Limits addon. 

I think there is also an issue related to the epic spawners feature where you can shift break a stacked spawner and receive the item with the appropriate stacked amount. The limits addon sometimes won't count this correctly and gets out of sync.

#### Server

 - OS: **Ubuntu 16.04**
 - Java version: **Java 8 (build 1.8.0_212)**

#### Plugins

```
Plugins (5): BentoBox, CMI, EpicSpawners, PermissionsEx*, Vault*
```

##### BentoBox and Addons

```
[Server thread/INFO]: Running PAPER 1.13.2.
[Server thread/INFO]: BentoBox version: 1.5.2
[Server thread/INFO]: Loaded Game Worlds:
[Server thread/INFO]: skyworld (Skyworld): Overworld, Nether, End
[Server thread/INFO]: Loaded Addons:
[Server thread/INFO]: Biomes 1.5.0.0 (ENABLED)
[Server thread/INFO]: BSkyBlock 1.5.0 (ENABLED)
[Server thread/INFO]: Challenges 0.7.5 (ENABLED)
[Server thread/INFO]: Level 1.5.0 (ENABLED)
[Server thread/INFO]: Limits 0.2.1-SNAPSHOT (ENABLED)
[Server thread/INFO]: WelcomeWarps 1.5.0 (ENABLED)
```

##### Configuration

 - Database: **YAML**

**Comment by tastybento** [comment]
Is there a way to file a bug with the EpicSpawners guys? It looks like their API has changed on that version but there's no change on [their GitHub for it](https://github.com/NextdoorPsycho/EpicSpawners/tree/master/EpicSpawners-API/src/main/java/com/songoda/epicspawners/api). It hasn't been updated for a year.

There's not much else I can do on this.

**Comment by Deathinflames** [comment]
Oh, they had actually swapped from github to gitlab some time ago. [This ](https://gitlab.com/Songoda/epicspawners)is where they make regular updates to it now.

**Comment by tastybento** [comment]
Aha! Okay, I’ll try and fix that then. Thanks!

**Comment by tastybento** [comment]
@Deathinflames can you try this version from the CI? https://ci.codemc.org/job/BentoBoxWorld/job/Limits/

I used the latest version of EpicSpawners API. I assume it'll work better.

**Comment by Tomvapor** [comment]
Hey @tastybento 
i have the same issue with EpicSpawners and BentoBox
i got the latest version on codemc from limits. you have another solution for me?

**Comment by Tomvapor** [comment]
`[23:08:35] [Server thread/ERROR]: Could not pass event SpawnerBreakEvent to BentoBox v1.7.0-SNAPSHOT-b1331
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at com.songoda.epicspawners.listeners.BlockListeners.onBlockBreak(BlockListeners.java:229) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:295) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:254) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:151) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1185) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.songoda.epicspawners.api.spawner.Spawner com.songoda.epicspawners.api.events.SpawnerBreakEvent.getSpawner()'
	at bentobox.addon.limits.listeners.EpicSpawnersListener.onBlockBreak(EpicSpawnersListener.java:29) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	... 29 more
`

**Comment by tastybento** [comment]
@Tomvapor What version of EpicSpawners?

**Comment by Tomvapor** [comment]
Version: STABLE 6.0.9
available here: https://songoda.com/marketplace/product/epicspawners-the-ultimate-spawner-plugin.13

**Comment by tastybento** [comment]
Yeah, I only just updated to 6.0.7. It's going to be a real pain to keep on having to support this plugin if the API keeps being incompatible. Okay, let's see whether it can be fixed...

**Comment by tastybento** [comment]
Can you try the latest build on the CI server and see if that works?

b0888d1e9d68200fdf172d8242d88ce60ae2b58e

**Comment by Tomvapor** [comment]
Hey,
we got the same error message again
`[08:41:28] [Server thread/ERROR]: Could not pass event SpawnerBreakEvent to BentoBox v1.7.0-SNAPSHOT-b1332
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at com.songoda.epicspawners.listeners.BlockListeners.onBlockBreak(BlockListeners.java:229) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:295) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:254) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:151) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1185) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.songoda.epicspawners.api.spawner.Spawner com.songoda.epicspawners.api.events.SpawnerBreakEvent.getSpawner()'
	at bentobox.addon.limits.listeners.EpicSpawnersListener.onBlockBreak(EpicSpawnersListener.java:29) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	... 29 more
`

**Comment by tastybento** [comment]
@Tomvapor I don't have access to that plugin so I'm working in the dark here. I'll PM you on Discord.

**Comment by tastybento** [comment]
Okay, fixed! Thanks!
