### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by BackWheel** [BentoBoxWorld/Limits#27]
This error occurs when I open the server and restart the bentobox plugin.

[09:35:40 ERROR]: [BentoBox] Please report this stack trace to the addon's author(s): tastybento
java.lang.NoSuchFieldError: TIPPED_ARROW
        at bentobox.addon.limits.commands.LimitPanel.<clinit>(LimitPanel.java:64) ~[?:?]
        at bentobox.addon.limits.Settings.<init>(Settings.java:28) ~[?:?]
        at bentobox.addon.limits.Limits.onEnable(Limits.java:40) ~[?:?]
        at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:168) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_211]
        at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:147) ~[?:?]
        at world.bentobox.bentobox.managers.AddonsManager.reloadAddons(AddonsManager.java:225) ~[?:?]
        at world.bentobox.bentobox.commands.BentoBoxReloadCommand.lambda$execute$0(BentoBoxReloadCommand.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-105]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.2.jar:git-Paper-105]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1129) ~[patched_1.14.2.jar:git-Paper-105]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-105]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-105]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-105]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

Below is my plugin version

[09:37:47 INFO]: Running PAPER 1.14.2.
[09:37:47 INFO]: Bentobox 版本：1.6.0-SNAPSHOT-b1194
[09:37:47 INFO]: 已加载游戏世界：
[09:37:47 INFO]: commands.bentobox.version.game-world
[09:37:47 INFO]: 已加载组件
[09:37:47 INFO]: Biomes 1.5.2.1-SNAPSHOT-b119
[09:37:47 INFO]: BSkyBlock 1.5.3-SNAPSHOT
[09:37:47 INFO]: Challenges 0.8.0-SNAPSHOT-#275
[09:37:47 INFO]: Level 1.5.1-SNAPSHOT
[09:37:47 INFO]: Limits 0.2.0-SNAPSHOT
[09:37:47 INFO]: WelcomeWarps 1.5.0

**Comment by tastybento** [comment]
Use Version 0.2.2. https://github.com/BentoBoxWorld/Limits/releases/tag/0.2.2
