### ISSUE TITLE
Could not pass event HangingPlaceEvent to BentoBox

### ISSUE THREAD

**Issue by mrfloris** [BentoBoxWorld/Limits#36]
#### Describe the bug

```
[19:53:05 ERROR]: Could not pass event HangingPlaceEvent to BentoBox v1.6.0-SNAPSHOT-b1311
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.ItemHanging.a(ItemHanging.java:38) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:163) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:511) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1222) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at world.bentobox.bentobox.managers.IslandWorldManager.getPermissionPrefix(IslandWorldManager.java:492) ~[?:?]
        at bentobox.addon.limits.listeners.EntityLimitListener.onBlock(EntityLimitListener.java:122) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor980.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        ... 18 more
[19:53:07 ERROR]: Could not pass event HangingPlaceEvent to BentoBox v1.6.0-SNAPSHOT-b1311
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.ItemHanging.a(ItemHanging.java:38) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:163) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:511) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1222) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at world.bentobox.bentobox.managers.IslandWorldManager.getPermissionPrefix(IslandWorldManager.java:492) ~[?:?]
        at bentobox.addon.limits.listeners.EntityLimitListener.onBlock(EntityLimitListener.java:122) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor980.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        ... 18 more
```

Not sure what the player is doing, they left when I got home, but the console was flooded with these after today's upgrade to the jenkin builds.

#### Steps to reproduce the behavior

no idea.

#### Expected behavior

n/a

#### Server

 - OS: macOS Mojave
 - Java version: 11

#### Plugins

```
we/wg/cmi/mv-core/bentobox
```

##### BentoBox and Addons

```
>bentobox version
[20:16:06 INFO]: Running SPIGOT 1.13.2.
[20:16:06 INFO]: BentoBox version: 1.6.0-SNAPSHOT-b1311
[20:16:06 INFO]: Database: JSON
[20:16:06 INFO]: Loaded Game Worlds:
[20:16:06 INFO]: acid (acid): Overworld, Nether, End
[20:16:06 INFO]: cave (cave): Overworld, Nether, End
[20:16:06 INFO]: skyblock (skyblock): Overworld, Nether, End
[20:16:06 INFO]: skygrid (skygrid): Overworld, Nether, End
[20:16:06 INFO]: Loaded Addons:
[20:16:06 INFO]: AcidIsland 1.6.0-SNAPSHOT (ENABLED)
[20:16:06 INFO]: BSkyBlock 1.6.0-SNAPSHOT (ENABLED)
[20:16:06 INFO]: CaveBlock ${version}${build.number} (ENABLED)
[20:16:06 INFO]: Level 1.6.0-SNAPSHOT (ENABLED)
[20:16:06 INFO]: Limits 1.6.0-SNAPSHOT (ENABLED)
[20:16:06 INFO]: MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
[20:16:06 INFO]: SkyGrid 1.6.0 (ENABLED)
[20:16:06 INFO]: WelcomeWarps 1.5.2-SNAPSHOT (ENABLED)
>
```

##### Configuration

 - Database: flatfile/json 

### Additional context

The only i can tell is that they were editing armor stands, they were in the non-bentobox world (world called general) and they were just playing as they would each day.

**Comment by tastybento** [comment]
Thanks!
