### ISSUE TITLE
Spawner break error with EpicSpawners

### ISSUE THREAD

**Issue by Tomvapor** [BentoBoxWorld/Limits#38]
Hi!

This error appears, when using the plugin with "EpicSpanwers (songoda)".
I've tried several versions of bentobox and addons but don't work.
Addons: BSkyBlock, Challanges, Level, Limits, MagicCobbleStoneGenerator
Software: Spigot-1.14.4

The error appears when i break a spawner ingame.

`[Server thread/ERROR]: Could not pass event SpawnerBreakEvent to BentoBox v1.7.0-SNAPSHOT-b1331
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at com.songoda.epicspawners.listeners.BlockListeners.onBlockBreak(BlockListeners.java:229) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:295) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:254) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:151) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1185) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.songoda.epicspawners.api.spawner.Spawner com.songoda.epicspawners.api.events.SpawnerBreakEvent.getSpawner()'
	at bentobox.addon.limits.listeners.EpicSpawnersListener.onBlockBreak(EpicSpawnersListener.java:29) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-368f4e9]
	... 29 more`

**Comment by Poslovitch** [comment]
Duplicate https://github.com/BentoBoxWorld/Limits/issues/25. Closing.
