### ISSUE TITLE
entitylimits expand with permissions

### ISSUE THREAD

**Issue by SirvydasS** [BentoBoxWorld/Limits#47]
**Is your feature request related to a problem? Please describe.**
Dont work entitylimits permissions. Example i give VIP a permission bskyblock.island.limit.hopper.222 and everything is ok, but bskyblock.island.limit.cow.222 dont work.

**Describe the solution you'd like**
Make entitylimits  permissions work.

**Additional context**
Using Limits-1.7.0-SNAPSHOT-b167

**Comment by tastybento** [comment]
I see the issue. Support for perm limits was not extended to include entities, so it's just covering blocks. Fixing...

**Comment by wellnesscookie** [comment]
I'm sorry, but is this fixed? I still can't expand the limits even with the **official 1.7.0** version.
I tried to use 1.9.0 version, but I am not sure if it is compatible with 1.8.0 BBox, for an example:
```
[21:30:44 INFO]: acBee issued server command: /bsb limits calc Manic12
[21:30:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'bsb limits calc Manic12' in world.bentobox.bskyblock.commands.AdminCommand(bsbadmin)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[patched_1.13.2.jar:git-Paper-652]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-652]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-652]
        at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.NoSuchMethodError: world.bentobox.bentobox.util.Util.getChunkAtAsync(Lorg/bukkit/World;II)Ljava/util/concurrent/CompletableFuture;
        at bentobox.addon.limits.commands.LimitsCalc.lambda$new$2(LimitsCalc.java:50) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at bentobox.addon.limits.commands.LimitsCalc.<init>(LimitsCalc.java:50) ~[?:?]
        at bentobox.addon.limits.commands.CalcCommand.calcLimits(CalcCommand.java:65) ~[?:?]
        at bentobox.addon.limits.commands.CalcCommand.execute(CalcCommand.java:54) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-652]
        ... 14 more
```

**Comment by SirvydasS** [comment]
Not yet. (sad tone)

**Comment by tastybento** [comment]
Please try latest build to confirm.

**Comment by SirvydasS** [comment]
Error is gone on login, but limits don't extend.

**Comment by tastybento** [comment]
Okay, it should work now.

**Comment by SirvydasS** [comment]
Yes! Working!
