### ISSUE TITLE
[Bug] /skyblock limits gives internal exception error

### ISSUE THREAD

**Issue by mrfloris** [BentoBoxWorld/Limits#64]
**Description**

In-game, when typing: /skyblock limits, it gives an internal exception error. 

**Steps to reproduce the behavior:**
1. Go to '...' Your skyblock
2. Click on '....' t to type
3. Scroll down to '....' nowhere. 
4. See error > nope .. just type: /is limits or /skyblock limits, whatever you have it set to. 

```
[16:10:19] [Server thread/INFO]: mrfloris issued server command: /skyblock limits
[16:10:19] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'skyblock limits' in world.bentobox.bskyblock.commands.IslandCommand(skyblock)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at world.bentobox.limits.commands.LimitPanel.getCount(LimitPanel.java:145) ~[?:?]
        at world.bentobox.limits.commands.LimitPanel.lambda$showLimits$2(LimitPanel.java:128) ~[?:?]
        at java.util.Map.forEach(Map.java:661) ~[?:?]
        at world.bentobox.limits.commands.LimitPanel.showLimits(LimitPanel.java:111) ~[?:?]
        at world.bentobox.limits.commands.PlayerCommand.execute(PlayerCommand.java:48) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-1339488-1816850]
        ... 16 more
```

**Expected behavior**

Give gui with limits. Not error

**Screenshots**

Just a red msg saying internal error

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): []  json
 - OS: [e.g. iOS] macOS Catalina
 - Java Version: [e.g. Java 8] java 11
 - BentoBox version: [e.g. 1.7.2.21] 1.11.1-SNAPSHOT-b1630 (tried in 1.15.0 and 1.15.1 and 1.15.2 with various bentobox versions and limits addon versions. has been failing for a while. tried with latest jenkins, still happens.
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
```
>bentobox version
[16:13:48] [Server thread/INFO]: Running SPIGOT 1.15.2.
[16:13:48] [Server thread/INFO]: BentoBox version: 1.11.1-SNAPSHOT-b1630
[16:13:48] [Server thread/INFO]: Database: JSON
[16:13:48] [Server thread/INFO]: Loaded Game Worlds:
[16:13:48] [Server thread/INFO]: acid (acid): Overworld, [nether_color]Nether, [end_color]End
[16:13:48] [Server thread/INFO]: cave (cave): Overworld, [nether_color]Nether, [end_color]End
[16:13:48] [Server thread/INFO]: skyblock (skyblock): Overworld, [nether_color]Nether, [end_color]End
[16:13:48] [Server thread/INFO]: skygrid (skygrid): Overworld, [nether_color]Nether, [end_color]End
[16:13:48] [Server thread/INFO]: Loaded Addons:
[16:13:48] [Server thread/INFO]: AcidIsland 1.11.1-SNAPSHOT-b626 (ENABLED)
[16:13:48] [Server thread/INFO]: Biomes 1.6.0.1-SNAPSHOT-b150 (ENABLED)
[16:13:48] [Server thread/INFO]: Border 1.0.3 (ENABLED)
[16:13:48] [Server thread/INFO]: BSkyBlock 1.11.1-SNAPSHOT-b589 (ENABLED)
[16:13:48] [Server thread/INFO]: CaveBlock 1.11.0 (ENABLED)
[16:13:48] [Server thread/INFO]: Challenges 0.9.0-SNAPSHOT-b397 (ENABLED)
[16:13:48] [Server thread/INFO]: ControlPanel 1.7.0-SNAPSHOT-#7 (ENABLED)
[16:13:48] [Server thread/INFO]: ExtraMobs 1.11.0.2 (ENABLED)
[16:13:48] [Server thread/INFO]: Greenhouses 1.0.0-SNAPSHOT-b117 (ENABLED)
[16:13:48] [Server thread/INFO]: Level 1.9.3-SNAPSHOT-b340 (ENABLED)
[16:13:48] [Server thread/INFO]: Likes 1.7.0-SNAPSHOT-b16 (ENABLED)
[16:13:48] [Server thread/INFO]: Limits 1.9.1-SNAPSHOT-b198 (ENABLED)
[16:13:48] [Server thread/INFO]: MagicCobblestoneGenerator 1.9.0-SNAPSHOT-b93 (ENABLED)
[16:13:48] [Server thread/INFO]: SkyGrid 1.11.1-SNAPSHOT-b310 (ENABLED)
[16:13:48] [Server thread/INFO]: Warps 1.9.3-SNAPSHOT-b221 (ENABLED)
```

other addons are multiverse-core, cmi, worldguard, worldedit, and bunch of proprietary stuff, and other gameplay plugins. But it happens on another server as well, with different batch of plugins. 

**Additional context**

**Comment by tastybento** [comment]
Did this just suddenly start happening, or did you update or something?

**Comment by tastybento** [comment]
The error is weird. It seems to be triggered by the Nether world being null, but that's quite odd and shouldn't happen. I'll add a null check in but it's not a root cause fix.

**Comment by mrfloris** [comment]
> Did this just suddenly start happening, or did you update or something?

It works during 1.15.1 for about a week. We went from older bentobox in 1.13.2 to newer 2019 release in 1.15.1

Now we're on spigot 1.15.2 and latest dev builds, it started happening about a week (or two) into 1.15.1 after the upgrade. Haven't been able to get it to work since. 

Yes, we dont use the nether worlds. I do believe i have it set off in the config for skyblock - we just want players to use the skyblock island. We use player rewards in order to get the impossible to get blocks and items so they have something to work towards to. 

If i can do something to help you debug this pls dont be shy to ask :)

**Comment by tastybento** [comment]
Okay, I see what the issue was. The config says that nether islands is on, but the nether world is off. This fix will solve that. Thanks.

**Comment by mrfloris** [comment]
Just a confirmation that this has indeed fixed it. Thank you for looking into this.
