### ISSUE TITLE
Issue with Paper and BentoBox

### ISSUE THREAD

**Issue by NOcode1** [BentoBoxWorld/Limits#81]
**Description**
When players create, goto, or leave an island the console gets a massive error message.

**Steps to reproduce the behavior:**
1. Run /is, /spawn, or /is warp (player)
2. Open console
3. See error

**Expected behavior**
A clear console without errors.

**Error**
`[10-May-2020 15:53:19] Could not pass event IslandEvent to BentoBox v1.12.0

[10-May-2020 15:53:19] java.lang.LinkageError: world/bentobox/challenges/config/Settings

[10-May-2020 15:53:19] at world.bentobox.challenges.listeners.ResetListener.onIslandReset(ResetListener.java:29) ~[?:?]

[10-May-2020 15:53:19] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor680.execute(Unknown Source) ~[?:?]

[10-May-2020 15:53:19] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at world.bentobox.bentobox.api.events.island.IslandEvent$IslandEventBuilder.build(IslandEvent.java:624) ~[?:?]

[10-May-2020 15:53:19] at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.lambda$handleEnterExit$1(EnterExitListener.java:82) ~[?:?]

[10-May-2020 15:53:19] at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242]

[10-May-2020 15:53:19] at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.handleEnterExit(EnterExitListener.java:74) ~[?:?]

[10-May-2020 15:53:19] at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.onTeleport(EnterExitListener.java:35) ~[?:?]

[10-May-2020 15:53:19] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source) ~[?:?]

[10-May-2020 15:53:19] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:768) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at world.bentobox.bentobox.paperlib.features.asyncteleport.AsyncTeleportPaper.lambda$teleportAsync$0(AsyncTeleportPaper.java:16) ~[?:?]

[10-May-2020 15:53:19] at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_242]

[10-May-2020 15:53:19] at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_242]

[10-May-2020 15:53:19] at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_242]

[10-May-2020 15:53:19] at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_242]

[10-May-2020 15:53:19] at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.lambda$null$8(CraftWorld.java:2478) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.WorldServer.doIfNotEntityTicking(WorldServer.java:69) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.lambda$getChunkAtAsync$9(CraftWorld.java:2478) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$bringToStatusAsync$7(ChunkProviderServer.java:423) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_242]

[10-May-2020 15:53:19] at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_242]

[10-May-2020 15:53:19] at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_242]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1001) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1048) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:601) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-229]

[10-May-2020 15:53:19] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Server Information:**

 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - Spigot Type: Paper 1.15.2 Latest
 - OS: Linux (Not sure what flavor)
 - Java Version: OpenJDK 1.8
 - BentoBox version: 1.12.0
 - Addons installed? Biomes 1.7.9, Border 1.0.7, BSkyblock 1.12.0, Challenges 0.8.2, Chat 1.0.5, ControlPanel 1.7.0, Level 1.9.3, MagicCobblestoneGenerator 1.7.0.2, Warps 1.9.3, 

 - Other plugins?
Admin-Chat*, AuctionHouse, BentoBox, BuycraftX, Citizens, ClearLag, CoreProtect, CrazyCrates, CrazyEnchantments, CustomHeads*, EnjinMinecraftPlugin, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, HolographicDisplays, LuckPerms, MandMMC-BanGUI*, MandMMCDiscord*, Multiverse-Core, NoHopperCraft*, OldCombatMechanics, OpenInv, PlaceholderAPI, PlayerListPlus*, ProtocolLib, ProtocolSupport, PsudoCommand, RankGrantPlus, RewardVoting*, SilkSpawners, SimpleBossBar*, Spartan, StackMob, SuperVanish, TeleportationTools*, Vault, ViaVersion*, VoidGenerator, VoidSpawn, Votifier*, WorldBorderAPI*, WorldEdit, WorldGuard

**Comment by BONNe** [comment]
I would suggest updating BentoBox to 1.13.x version.
Also, the error message (fixed in 1.13) is telling that you have 2 challenges.jar addon in addons folder.
